### ISSUE TITLE
mqtt_admin table type error in cluster environment

### ISSUE THREAD

**Issue by turtleDeng** [emqtt/emq_dashboard#79]
1. start emqttd1@127.0.0.1
2. start emqttd2@127.0.0.1
3. cluster join emqttd1@127.0.0.1

mqtt_admin table is emqttd1@127.0.0.1 disc_copies
mqtt_admin table is emqttd2@127.0.0.1 ram_copies

**Comment by emqplus** [comment]
Commit: https://github.com/emqtt/emq_dashboard/commit/e18358e6cef24415a8af0faf70cfb865d10ee335
